### ISSUE TITLE
Spelling and stylistic recommendations

### ISSUE THREAD

**Issue by daniel-koronthaly** [evrhel/uw-website#1]
- [x] Pursue is misspelled as persue [Dictionary reference](https://www.merriam-webster.com/dictionary/pursue)
- [x] Recommend deletion of "Hi!" right after "Hello!" in the intro
- [x] "MatrixUtil is a library written in C++ to handle both vector and matrix calculations and quaternion
calculations" uses the word both and mentions three things when both is typically used to refer to two things [Dictionary reference](https://www.merriam-webster.com/dictionary/both)
- [x] "lscript is an in-development statically typed scripting language (kind of)" remove (kind of)
- [x] Fix broken spacing in both code blocks such as classMain or usinglscript.io
![image](https://user-images.githubusercontent.com/60303774/234724546-24c323cd-9f43-495f-990c-fe27008a807f.png)

**Comment by evrhel** [comment]
Fixed in commit [5e08926](https://github.com/evrhel/uw-website/commit/5e08926276f5ee018195eb722308b0c8d1e17b4f)
